#!/usr/bin/env node
/*
 * Releases the plugin and brings the website along in one action.
 *
 * Publishing happens in CI, not here. npm has retired the tokens that could
 * write without a one-time code, and this account has no authenticator, so a
 * local `npm publish` can no longer succeed at all. Instead the tag push hands
 * off to .github/workflows/publish.yml, which npm trusts through OIDC — no
 * token, nothing stored, nothing to rotate.
 *
 * That makes the release asynchronous, so this waits: it polls the registry
 * until the new version appears, and only then updates the website. The two
 * are one release — polytheme.dev's stylesheet is generated by the published
 * package at build time, so the site is the first real consumer of every
 * version, and building it here means a bad publish is caught on this machine.
 *
 * Nothing touches the website until npm actually serves the new version, so a
 * failed CI run leaves the site exactly where it was.
 *
 * A run interrupted after the bump resumes from the version already committed
 * and tagged rather than bumping past it.
 *
 *   npm run release -- patch                  1.0.7 -> 1.0.8
 *   npm run release -- minor                  1.0.7 -> 1.1.0
 *   npm run release -- 1.2.0                  an exact version
 *   npm run release -- patch --dry-run        rehearse, writing nothing
 *   npm run release -- patch --no-site        leave the website alone
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const PLUGIN = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = resolve(PLUGIN, "..", "Website");
const { name } = JSON.parse(readFileSync(join(PLUGIN, "package.json"), "utf8"));

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const skipSite = args.includes("--no-site");
const bump = args.find((a) => !a.startsWith("--"));

if (!bump) {
  console.error("usage: npm run release -- <patch|minor|major|x.y.z> [--dry-run] [--no-site]");
  process.exit(1);
}

const sh = (cmd, cmdArgs, cwd = PLUGIN) =>
  execFileSync(cmd, cmdArgs, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
const loud = (cmd, cmdArgs, cwd = PLUGIN, env) =>
  execFileSync(cmd, cmdArgs, { cwd, stdio: "inherit", env: { ...process.env, ...env } });

const step = (message) => console.log(`\n── ${message}`);
const die = (message) => {
  console.error(`\n✗ ${message}`);
  process.exit(1);
};

/** Refuses to release from a repo that is not exactly what origin has. */
function assertReleasable(repo, label) {
  if (sh("git", ["status", "--porcelain"], repo)) {
    die(`${label} has uncommitted changes. Commit or stash them first.`);
  }
  const branch = sh("git", ["rev-parse", "--abbrev-ref", "HEAD"], repo);
  if (branch !== "main") die(`${label} is on ${branch}, not main.`);

  sh("git", ["fetch", "origin", "main"], repo);
  const [ahead, behind] = sh("git", ["rev-list", "--left-right", "--count", "HEAD...origin/main"], repo)
    .split(/\s+/)
    .map(Number);
  if (behind > 0) die(`${label} is ${behind} commit(s) behind origin/main. Pull first.`);
  return { ahead };
}

step("checking the plugin repo");
assertReleasable(PLUGIN, "The plugin repo");

const haveSite = !skipSite && existsSync(join(SITE, "package.json"));
if (!skipSite && !haveSite) {
  console.log(`· no Website checkout at ${SITE} — the site will not be updated`);
}
if (haveSite) {
  step("checking the website repo");
  assertReleasable(SITE, "The website repo");
}

/*
 * A publish that failed after the bump leaves the version committed and tagged
 * but absent from the registry. Bumping again there would burn a version
 * number for nothing and leave a tag pointing at something unpublished, so the
 * run picks up where it stopped instead.
 */
const current = JSON.parse(readFileSync(join(PLUGIN, "package.json"), "utf8")).version;
const tagged = sh("git", ["tag", "--list", `v${current}`]) === `v${current}`;
let publishedAlready = true;
try {
  sh("npm", ["view", `${name}@${current}`, "version"]);
} catch {
  publishedAlready = false;
}
const resuming = tagged && !publishedAlready;

step("running the tests");
loud("npm", ["test"]);

step("building");
loud("npm", ["run", "build"]);

if (dryRun) {
  /*
   * Worked out here rather than asked of npm: `npm version --dry-run` still
   * writes package.json and package-lock.json on this npm, which makes it
   * useless for a rehearsal — the one thing a dry run must never do is leave
   * the repo changed.
   */
  if (resuming) {
    console.log(
      `\n✓ dry run — ${current} is committed and tagged but not on npm,` +
        `\n  so a real run would publish it as-is${haveSite ? " and update the website" : ""}`,
    );
    console.log("  nothing was written; drop --dry-run to do it for real");
    process.exit(0);
  }

  const [major, minor, patch] = current.split(".").map(Number);
  const next =
    bump === "major" ? `${major + 1}.0.0`
    : bump === "minor" ? `${major}.${minor + 1}.0`
    : bump === "patch" ? `${major}.${minor}.${patch + 1}`
    : bump;

  console.log(`\n✓ dry run — would publish ${current} -> ${next}${haveSite ? " and update the website" : ""}`);
  console.log("  nothing was written; drop --dry-run to do it for real");
  process.exit(0);
}

let version;
if (resuming) {
  step(`resuming ${current}`);
  console.log("  already committed and tagged by an earlier run; not bumping again");
  version = current;
} else {
  step(`bumping the version (${bump})`);
  // `npm version` writes package.json, commits and tags in one go.
  version = sh("npm", ["version", bump, "-m", "Release %s"]).replace(/^v/, "");
  console.log(`  ${version}`);
}

step("pushing the plugin — this is what triggers the publish");
/*
 * A tag already on the remote fires no push event, so the workflow would never
 * start and the wait below would time out for no visible reason.
 */
const onRemote = sh("git", ["ls-remote", "--tags", "origin", `v${version}`]) !== "";
loud("git", ["push", "--follow-tags", "origin", "main"]);
if (onRemote) {
  console.log(
    `  ! v${version} was already on origin, so no new workflow run was triggered.\n` +
      `    Start one by hand if the previous run failed:\n` +
      `      gh workflow run publish.yml -f tag=v${version}`,
  );
}

/*
 * Poll rather than watch the Actions run: the registry is the thing that
 * actually matters, and a green workflow that somehow published nothing should
 * still count as a failure here.
 */
step(`waiting for npm to serve ${version}`);
console.log(`  https://github.com/Polytheme/Polytheme/actions`);

const deadline = Date.now() + 15 * 60 * 1000;
let live = false;
while (Date.now() < deadline) {
  try {
    sh("npm", ["view", `${name}@${version}`, "version"]);
    live = true;
    break;
  } catch {
    process.stdout.write(".");
    await new Promise((r) => setTimeout(r, 10_000));
  }
}
console.log("");

if (!live) {
  die(
    `${version} has not appeared on npm after 15 minutes.\n` +
      `  The tag is pushed, so check the run:\n` +
      `      https://github.com/Polytheme/Polytheme/actions\n\n` +
      `  Nothing was done to the website — polytheme.dev is untouched.\n` +
      `  Once the publish lands, re-run this and it will pick up from here.`,
  );
}
console.log(`  ✓ npm is serving ${version}`);

if (!haveSite) {
  console.log(`\n✓ published ${version}. The website was not updated.`);
  process.exit(0);
}

step(`updating the website to ${version}`);
loud("npm", ["install", "--save-dev", `polytheme@${version}`], SITE);

step("rebuilding the website against the new version");
try {
  // Strict here: the site's own guard only warns so that a flaky registry
  // cannot break a Cloudflare deploy, but during a release a version mismatch
  // means the install above did not take, and shipping past that is the whole
  // thing this script exists to prevent.
  loud("npm", ["run", "build"], SITE, { STRICT_PLUGIN_VERSION: "1" });
} catch {
  die(
    `${version} is published, but the website fails to build against it.\n` +
      `  The site has NOT been pushed, so polytheme.dev is still on the previous version.\n` +
      `  Investigate in ${SITE}, then commit and push once it builds.`,
  );
}

const siteName = JSON.parse(readFileSync(join(SITE, "package.json"), "utf8")).name;
if (!sh("git", ["status", "--porcelain"], SITE)) {
  console.log(`· ${siteName} was already on ${version} — nothing to commit`);
} else {
  step("pushing the website");
  loud("git", ["add", "package.json", "package-lock.json"], SITE);
  loud("git", ["commit", "-m", `Build against polytheme ${version}`], SITE);
  loud("git", ["push", "origin", "main"], SITE);
}

console.log(`\n✓ published ${version} and deployed the site against it`);
