#!/usr/bin/env node
/*
 * Publishes the plugin and brings the website along in one action.
 *
 * The two are one release, not two: polytheme.dev's stylesheet is generated by
 * the published package at build time, so the site is the first real consumer
 * of every version. Building it here means a broken publish fails on this
 * machine rather than on the live site.
 *
 * Nothing is pushed until npm has accepted the publish, so a failure part-way
 * leaves a local commit and tag to amend rather than a version the world can
 * see but not install.
 *
 *   npm run release -- patch        1.0.7 -> 1.0.8
 *   npm run release -- minor        1.0.7 -> 1.1.0
 *   npm run release -- 1.2.0        an exact version
 *   npm run release -- patch --dry-run   rehearse without publishing
 *   npm run release -- patch --no-site   leave the website alone
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const PLUGIN = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = resolve(PLUGIN, "..", "Website");

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const skipSite = args.includes("--no-site");
const bump = args.find((a) => !a.startsWith("--"));

if (!bump) {
  console.error("usage: npm run release -- <patch|minor|major|x.y.z> [--dry-run] [--no-site]");
  process.exit(1);
}

const sh = (cmd, cmdArgs, cwd = PLUGIN) =>
  execFileSync(cmd, cmdArgs, { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
const loud = (cmd, cmdArgs, cwd = PLUGIN, env) =>
  execFileSync(cmd, cmdArgs, { cwd, stdio: "inherit", env: { ...process.env, ...env } });

const step = (message) => console.log(`\n── ${message}`);
const die = (message) => {
  console.error(`\n✗ ${message}`);
  process.exit(1);
};

/** Refuses to release from a repo that is not exactly what origin has. */
function assertReleasable(repo, label) {
  if (sh("git", ["status", "--porcelain"], repo)) {
    die(`${label} has uncommitted changes. Commit or stash them first.`);
  }
  const branch = sh("git", ["rev-parse", "--abbrev-ref", "HEAD"], repo);
  if (branch !== "main") die(`${label} is on ${branch}, not main.`);

  sh("git", ["fetch", "origin", "main"], repo);
  const [ahead, behind] = sh("git", ["rev-list", "--left-right", "--count", "HEAD...origin/main"], repo)
    .split(/\s+/)
    .map(Number);
  if (behind > 0) die(`${label} is ${behind} commit(s) behind origin/main. Pull first.`);
  return { ahead };
}

step("checking the plugin repo");
assertReleasable(PLUGIN, "The plugin repo");

const haveSite = !skipSite && existsSync(join(SITE, "package.json"));
if (!skipSite && !haveSite) {
  console.log(`· no Website checkout at ${SITE} — the site will not be updated`);
}
if (haveSite) {
  step("checking the website repo");
  assertReleasable(SITE, "The website repo");
}

step("running the tests");
loud("npm", ["test"]);

step("building");
loud("npm", ["run", "build"]);

if (dryRun) {
  /*
   * Worked out here rather than asked of npm: `npm version --dry-run` still
   * writes package.json and package-lock.json on this npm, which makes it
   * useless for a rehearsal — the one thing a dry run must never do is leave
   * the repo changed.
   */
  const current = JSON.parse(readFileSync(join(PLUGIN, "package.json"), "utf8")).version;
  const [major, minor, patch] = current.split(".").map(Number);
  const next =
    bump === "major" ? `${major + 1}.0.0`
    : bump === "minor" ? `${major}.${minor + 1}.0`
    : bump === "patch" ? `${major}.${minor}.${patch + 1}`
    : bump;

  console.log(`\n✓ dry run — would publish ${current} -> ${next}${haveSite ? " and update the website" : ""}`);
  console.log("  nothing was written; drop --dry-run to do it for real");
  process.exit(0);
}

step(`bumping the version (${bump})`);
// `npm version` writes package.json, commits and tags in one go.
const version = sh("npm", ["version", bump, "-m", "Release %s"]).replace(/^v/, "");
console.log(`  ${version}`);

step("publishing to npm");
try {
  loud("npm", ["publish"]);
} catch {
  die(
    `npm publish failed. The bump commit and tag v${version} are local only.\n` +
      `  Fix the cause, then:  git reset --hard HEAD~1 && git tag -d v${version}`,
  );
}

step("pushing the plugin");
loud("git", ["push", "--follow-tags", "origin", "main"]);

if (!haveSite) {
  console.log(`\n✓ published ${version}. The website was not updated.`);
  process.exit(0);
}

step(`updating the website to ${version}`);
loud("npm", ["install", "--save-dev", `polytheme@${version}`], SITE);

step("rebuilding the website against the new version");
try {
  // Strict here: the site's own guard only warns so that a flaky registry
  // cannot break a Cloudflare deploy, but during a release a version mismatch
  // means the install above did not take, and shipping past that is the whole
  // thing this script exists to prevent.
  loud("npm", ["run", "build"], SITE, { STRICT_PLUGIN_VERSION: "1" });
} catch {
  die(
    `${version} is published, but the website fails to build against it.\n` +
      `  The site has NOT been pushed, so polytheme.dev is still on the previous version.\n` +
      `  Investigate in ${SITE}, then commit and push once it builds.`,
  );
}

const siteName = JSON.parse(readFileSync(join(SITE, "package.json"), "utf8")).name;
if (!sh("git", ["status", "--porcelain"], SITE)) {
  console.log(`· ${siteName} was already on ${version} — nothing to commit`);
} else {
  step("pushing the website");
  loud("git", ["add", "package.json", "package-lock.json"], SITE);
  loud("git", ["commit", "-m", `Build against polytheme ${version}`], SITE);
  loud("git", ["push", "origin", "main"], SITE);
}

console.log(`\n✓ published ${version} and deployed the site against it`);
